Objectives/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :goals

end

Objectives/app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
end

Objectives/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  has_many(
    :goals,
    class_name: 'Goal',
    foreign_key: :user_id,
    primary_key: :id
  )

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

Objectives/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def log_out
    if current_user
      current_user.reset_session_token!
    end
      session[:session_token] = nil

  end

  def logged_in?
    !!current_user
  end

  def require_log_in
    redirect_to new_session_url unless logged_in?
  end
end

Objectives/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new

  end

  def create
    @goal = Goal.new(goal_params)

    if @goal.save
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end


  private

  def goal_params
    params.require(:goal).permit(:user_id, :body)

  end
end

Objectives/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    if @user.nil?
      
      flash.now[:errors] = ["Invalid username/password combination"]
      render :new

    else
      log_in(@user)
      redirect_to user_url(@user.id)

    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

Objectives/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show

  end
  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Objectives/app/helpers/application_helper.rb
module ApplicationHelper
end

Objectives/app/helpers/goals_helper.rb
module GoalsHelper
end

Objectives/app/helpers/users_helper.rb
module UsersHelper
end

Objectives/app/views/goals/new.html.erb
<h1>Add a new goal</h1>

<form action="<%= goals_url %>" method="post">
  <label>Goal
    <input type="text" name="goal[body]">
  </label>

  <input type="radio" name="goal[goal_private]" value=" <%= checked  %>">

  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">

  <button>Create goal</button>
</form>

Objectives/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Objectives</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= current_user.username %>
    <br>
    <%= button_to "Sign out", session_url, method: :delete %>
  <% else %>
     <a href="<%= new_session_url %>">Log in</a>
  <% end %>

<%= yield %>

</body>
</html>

Objectives/app/views/users/new.html.erb
<h1>Create User</h1>

<form  action="<%= users_url %>" method="post">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" value="Create User">
  
</form>

Objectives/app/views/users/show.html.erb
<h1>Homepage</h1>
<br>

<ul>
  <% @user.goals.each do |goal| %>
    <li>
        <%= goal.body %>
    </li>
  <% end %>
</ul>

<a href="<%= new_goal_url %>">New goal</a>